### ISSUE TITLE
how to change the features? 

### ISSUE THREAD

**Issue by waterwheel31** [ykang/tsgeneration#4] opened 2019-02-09 08:37 UTC
I found this generator interesting, and tried to generate time series data. 
However, when I tried to add one feature from the sample, I am stacked. How can I add features? 

Following is the code to try to add 'seasonal.strength', but I found an error saying
"task 1 failed - "object 'seasonal.strength' of mode 'function' was not found"
How can I do? 

Plus, how can I do for other features which are on the paper (Kang, Hyndman, Li 2018) ? 

--------------------
x <- generate_ts_with_target(n = 2, 
				     ts.length = 360, 
                             freq = 1, 
                             seasonal = 0,
                             features = c('entropy', 'stl_features','seasonal.strength'),
                             selected.features = c('entropy', 'trend','seasonal.strength'),
                             target = c(0.2 0.9, 0.5)
                             )

**Comment by feng-li** [comment] 2019-02-11 09:45
Duplicate of #3

The argument `features`  should be a vector of **function** names. These functions are operations of time series features. `x_acf1` comes from the outputs of the `acf_features` function in the package [`tsfeatures`](https://github.com/robjhyndman/tsfeatures). Also, the `stl_features` function in the package `tsfeatures` outputs a vector of time series feature including trend, linearity, seasonal_strength, etc.
In your case, the argument `features` can be set as `c('stl_features', 'acf_features', 'entropy', 'lumpiness', 'flat_spots', 'crossing_points', 'max_kl_shift', 'max_level_shift', 'max_var_shift', 'mean', 'var')`.

_Originally posted by @ykang in https://github.com/ykang/tsgeneration/issues/3#issuecomment-427557228_

**Closed as completed** 2019-02-11 09:45 UTC
