### ISSUE TITLE
Error in unserialize(socklist[[n]]) : error reading from connection

### ISSUE THREAD

**Issue by ru81git454** [ykang/tsgeneration#15] opened 2020-03-12 06:12 UTC
Hi, I face another problem is when i set parameter 'parallel=TRUE', it usually shows error
'Error in unserialize(socklist[[n]]) : error reading from connection'
but 'parallel=FALSE'
Below is the console record.

` features_groups$compengine_all`
 [1] "embed2_incircle_1"              "embed2_incircle_2"              "ac_9"                          
 [4] "firstmin_ac"                    "trev_num"                       "motiftwo_entro3"               
 [7] "walker_propcross"               "localsimple_mean1"              "localsimple_lfitac"            
[10] "sampen_first"                   "std1st_der"                     "spreadrandomlocal_meantaul_50" 
[13] "spreadrandomlocal_meantaul_ac2" "histogram_mode_10"              "outlierinclude_mdrmd"          
[16] "fluctanal_prop_r1"             
` ts_features_compengine_sample[features_groups$compengine_all]`
A tibble: 1 x 16
  embed2_incircle… embed2_incircle…  ac_9 firstmin_ac trev_num motiftwo_entro3 walker_propcross localsimple_mea…
             <dbl>            <dbl> <dbl>       <dbl>    <dbl>           <dbl>            <dbl>            <dbl>
1            0.397            0.698 0.357           5   0.0916            1.48            0.176                2
 … with 8 more variables: localsimple_lfitac <dbl>, sampen_first <dbl>, std1st_der <dbl>,
   spreadrandomlocal_meantaul_50 <dbl>, spreadrandomlocal_meantaul_ac2 <dbl>, histogram_mode_10 <dbl>,
   outlierinclude_mdrmd <dbl>, fluctanal_prop_r1 <dbl>
```
x <- generate_ts_with_target(n = 10, ts.length = 120, freq = 1, seasonal = 0,
                              features = c('compengine'), selected.features = c(features_groups$compengine_all),
                              target=c(ts_features_compengine_sample[features_groups$compengine_all]),  
parallel=TRUE)
```
GA | iter = 1 | Mean = -66.852672 | Best =  -7.368517
GA | iter = 2 | Mean = -36.005346 | Best =  -5.533316
GA | iter = 3 | Mean = -20.992213 | Best =  -2.073057
GA | iter = 4 | Mean = -20.871916 | Best =  -2.073057
GA | iter = 5 | Mean = -9.784385 | Best = -2.073057
GA | iter = 6 | Mean = -9.310147 | Best = -2.073057
GA | iter = 7 | Mean = -8.341019 | Best = -2.073057
GA | iter = 8 | Mean = -9.003553 | Best = -2.073057
GA | iter = 9 | Mean = -7.406495 | Best = -2.069576
GA | iter = 10 | Mean = -5.431695 | Best = -2.069576
GA | iter = 11 | Mean = -7.154380 | Best = -2.069576
GA | iter = 12 | Mean = -7.260493 | Best = -2.069576
GA | iter = 13 | Mean = -7.944805 | Best = -2.069576
GA | iter = 14 | Mean = -6.684181 | Best = -2.069576
GA | iter = 15 | Mean = -9.766155 | Best = -2.069576
GA | iter = 16 | Mean = -13.365212 | Best =  -2.069576
GA | iter = 17 | Mean = -5.623767 | Best = -2.069576
GA | iter = 18 | Mean = -5.163883 | Best = -1.879883
GA | iter = 19 | Mean = -5.697692 | Best = -1.774704
GA | iter = 20 | Mean = -6.464667 | Best = -1.774704
GA | iter = 21 | Mean = -7.519872 | Best = -1.774704
GA | iter = 22 | Mean = -5.739485 | Best = -1.774704
GA | iter = 23 | Mean = -4.626605 | Best = -1.774704
GA | iter = 24 | Mean = -5.708493 | Best = -1.774704
GA | iter = 25 | Mean = -5.907762 | Best = -1.774704
GA | iter = 26 | Mean = -5.214543 | Best = -1.774704
GA | iter = 27 | Mean = -5.536255 | Best = -1.774704
GA | iter = 28 | Mean = -4.851290 | Best = -1.774704
GA | iter = 29 | Mean = -4.474448 | Best = -1.774704
GA | iter = 30 | Mean = -4.135490 | Best = -1.774704
Error in unserialize(socklist[[n]]) : error reading from connection
```
 x <- generate_ts_with_target(n = 1, ts.length = 120, freq = 1, seasonal = 0,
                             features = c('compengine'), selected.features = c(features_groups$compengine_all),
                              target=c(ts_features_compengine_sample[features_groups$compengine_all]),  parallel=TRUE)
```
GA | iter = 1 | Mean = -49.430088 | Best =  -4.613416
GA | iter = 2 | Mean = -27.054705 | Best =  -4.337821
GA | iter = 3 | Mean = -16.311539 | Best =  -4.337821
GA | iter = 4 | Mean = -16.540429 | Best =  -4.337821
GA | iter = 5 | Mean = -17.747687 | Best =  -2.039363
GA | iter = 6 | Mean = -11.495462 | Best =  -2.039363
GA | iter = 7 | Mean = -11.018104 | Best =  -2.039363
GA | iter = 8 | Mean = -11.571113 | Best =  -2.039363
GA | iter = 9 | Mean = -11.335135 | Best =  -2.039363
GA | iter = 10 | Mean = -7.523986 | Best = -2.039363
GA | iter = 11 | Mean = -7.242757 | Best = -2.039363
GA | iter = 12 | Mean = -8.076067 | Best = -2.039363
GA | iter = 13 | Mean = -7.031409 | Best = -2.039363
GA | iter = 14 | Mean = -8.049328 | Best = -2.039363
GA | iter = 15 | Mean = -7.761941 | Best = -2.039363
GA | iter = 16 | Mean = -9.741822 | Best = -1.908006
GA | iter = 17 | Mean = -10.360151 | Best =  -1.908006
GA | iter = 18 | Mean = -8.552470 | Best = -1.908006
GA | iter = 19 | Mean = -11.437778 | Best =  -1.908006
GA | iter = 20 | Mean = -6.728062 | Best = -1.908006
GA | iter = 21 | Mean = -6.309885 | Best = -1.908006
GA | iter = 22 | Mean = -6.052231 | Best = -1.908006
GA | iter = 23 | Mean = -5.948056 | Best = -1.908006
GA | iter = 24 | Mean = -6.822859 | Best = -1.908006
GA | iter = 25 | Mean = -6.900220 | Best = -1.908006
GA | iter = 26 | Mean = -5.595469 | Best = -1.908006
GA | iter = 27 | Mean = -7.945233 | Best = -1.908006
GA | iter = 28 | Mean = -9.488775 | Best = -1.908006
Error in unserialize(socklist[[n]]) : error reading from connection
 ```
x <- generate_ts_with_target(n = 1, ts.length = 120, freq = 1, seasonal = 0,
+                              features = c('compengine'), selected.features = c(features_groups$compengine_all),
+                              target=c(ts_features_compengine_sample[features_groups$compengine_all]),  parallel=FALSE)
```
GA | iter = 1 | Mean = -54.585013 | Best =  -4.042123
GA | iter = 2 | Mean = -38.223307 | Best =  -3.953552
GA | iter = 3 | Mean = -22.802254 | Best =  -2.916697
GA | iter = 4 | Mean = -9.308311 | Best = -2.916697
GA | iter = 5 | Mean = -8.455406 | Best = -2.616656
GA | iter = 6 | Mean = -7.708090 | Best = -2.616656
GA | iter = 7 | Mean = -10.237694 | Best =  -2.204324
GA | iter = 8 | Mean = -12.561889 | Best =  -2.204324
GA | iter = 9 | Mean = -10.655380 | Best =  -2.204324
GA | iter = 10 | Mean = -8.648677 | Best = -2.204324
GA | iter = 11 | Mean = -5.826070 | Best = -2.204324
GA | iter = 12 | Mean = -6.234029 | Best = -2.204324
GA | iter = 13 | Mean = -11.623634 | Best =  -2.204324
GA | iter = 14 | Mean = -6.075097 | Best = -2.204324
GA | iter = 15 | Mean = -5.854861 | Best = -2.204324
GA | iter = 16 | Mean = -6.772335 | Best = -2.204324
GA | iter = 17 | Mean = -7.415923 | Best = -2.204324
GA | iter = 18 | Mean = -5.483947 | Best = -2.204324
GA | iter = 19 | Mean = -6.113520 | Best = -2.204324
GA | iter = 20 | Mean = -6.505165 | Best = -2.204324
GA | iter = 21 | Mean = -5.618576 | Best = -2.204324
GA | iter = 22 | Mean = -6.920597 | Best = -2.204324
GA | iter = 23 | Mean = -6.989805 | Best = -2.077239
GA | iter = 24 | Mean = -6.392787 | Best = -2.077239
GA | iter = 25 | Mean = -6.839221 | Best = -2.077239
GA | iter = 26 | Mean = -6.682474 | Best = -2.077239
GA | iter = 27 | Mean = -9.302662 | Best = -2.077239
GA | iter = 28 | Mean = -6.081294 | Best = -2.077239
GA | iter = 29 | Mean = -7.560041 | Best = -2.077239
GA | iter = 30 | Mean = -8.463644 | Best = -2.077239
GA | iter = 31 | Mean = -12.264256 | Best =  -2.077239
GA | iter = 32 | Mean = -9.668713 | Best = -2.077239
GA | iter = 33 | Mean = -9.258544 | Best = -2.077239
GA | iter = 34 | Mean = -9.029584 | Best = -2.077239
GA | iter = 35 | Mean = -6.422915 | Best = -2.077239
GA | iter = 36 | Mean = -7.140980 | Best = -2.077239
GA | iter = 37 | Mean = -7.501049 | Best = -2.077239
GA | iter = 38 | Mean = -7.000897 | Best = -2.077239
GA | iter = 39 | Mean = -6.634549 | Best = -2.077239
GA | iter = 40 | Mean = -6.482912 | Best = -2.077239
GA | iter = 41 | Mean = -5.740218 | Best = -2.077239
GA | iter = 42 | Mean = -8.124309 | Best = -2.077239
GA | iter = 43 | Mean = -8.386757 | Best = -1.871865
GA | iter = 44 | Mean = -6.137567 | Best = -1.871865
GA | iter = 45 | Mean = -7.317306 | Best = -1.871865
GA | iter = 46 | Mean = -8.942302 | Best = -1.871865
GA | iter = 47 | Mean = -10.471457 | Best =  -1.871865
GA | iter = 48 | Mean = -11.379822 | Best =  -1.871865
GA | iter = 49 | Mean = -8.062991 | Best = -1.871865
GA | iter = 50 | Mean = -10.785102 | Best =  -1.871865
GA | iter = 51 | Mean = -7.702994 | Best = -1.871865
GA | iter = 52 | Mean = -6.632111 | Best = -1.871865
GA | iter = 53 | Mean = -5.161943 | Best = -1.871865
GA | iter = 54 | Mean = -6.020751 | Best = -1.871865
GA | iter = 55 | Mean = -5.375976 | Best = -1.871865
GA | iter = 56 | Mean = -9.676868 | Best = -1.871865
GA | iter = 57 | Mean = -4.718812 | Best = -1.871865
GA | iter = 58 | Mean = -5.374955 | Best = -1.722591
GA | iter = 59 | Mean = -7.656259 | Best = -1.722591
GA | iter = 60 | Mean = -7.168374 | Best = -1.722591
GA | iter = 61 | Mean = -5.362479 | Best = -1.722591
GA | iter = 62 | Mean = -6.890446 | Best = -1.722591
GA | iter = 63 | Mean = -6.063577 | Best = -1.722591
GA | iter = 64 | Mean = -7.901720 | Best = -1.722591
GA | iter = 65 | Mean = -5.642867 | Best = -1.722591
GA | iter = 66 | Mean = -7.087705 | Best = -1.722591
GA | iter = 67 | Mean = -4.660895 | Best = -1.722591
GA | iter = 68 | Mean = -6.963794 | Best = -1.722591
GA | iter = 69 | Mean = -5.137820 | Best = -1.722591
GA | iter = 70 | Mean = -7.011831 | Best = -1.722591
GA | iter = 71 | Mean = -4.755455 | Best = -1.722591
GA | iter = 72 | Mean = -7.830152 | Best = -1.722591
GA | iter = 73 | Mean = -6.400217 | Best = -1.722591
GA | iter = 74 | Mean = -6.539753 | Best = -1.722591
GA | iter = 75 | Mean = -4.825075 | Best = -1.722591
GA | iter = 76 | Mean = -6.460761 | Best = -1.722591
GA | iter = 77 | Mean = -5.713546 | Best = -1.722591
GA | iter = 78 | Mean = -6.995405 | Best = -1.722591
GA | iter = 79 | Mean = -5.986383 | Best = -1.722591
GA | iter = 80 | Mean = -6.774339 | Best = -1.722591
GA | iter = 81 | Mean = -8.919732 | Best = -1.722591
GA | iter = 82 | Mean = -7.738917 | Best = -1.722591
GA | iter = 83 | Mean = -6.162386 | Best = -1.722591
GA | iter = 84 | Mean = -6.327214 | Best = -1.722591
GA | iter = 85 | Mean = -6.780196 | Best = -1.722591
GA | iter = 86 | Mean = -7.488970 | Best = -1.722591
GA | iter = 87 | Mean = -7.081700 | Best = -1.722591
There were 50 or more warnings (use warnings() to see the first 50)

**Comment by ru81git454** [comment] 2020-04-02 15:39
![image](https://user-images.githubusercontent.com/34761696/78268586-f956f500-753a-11ea-9af2-1584a0c02c7f.png)
Hi, using the same code, some time i face different error issues during GA iteration.

**Comment by feng-li** [comment] 2020-07-13 00:34
It seems a parallelization problem caused by other packages. Closed this issue.

**Closed as completed by feng-li** 2020-07-13 00:34 UTC
